-- begin BIDEMO_CUSTOMER
alter table BIDEMO_CUSTOMER add constraint FK_BIDEMO_CUSTOMER_CITY foreign key (CITY_ID) references BIDEMO_CITY(ID)^
create index IDX_BIDEMO_CUSTOMER_CITY on BIDEMO_CUSTOMER (CITY_ID)^
-- end BIDEMO_CUSTOMER
-- begin BIDEMO_ORDER
alter table BIDEMO_ORDER add constraint FK_BIDEMO_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references BIDEMO_CUSTOMER(ID)^
create index IDX_BIDEMO_ORDER_CUSTOMER on BIDEMO_ORDER (CUSTOMER_ID)^
-- end BIDEMO_ORDER
-- begin BIDEMO_PRODUCT
alter table BIDEMO_PRODUCT add constraint FK_BIDEMO_PRODUCT_PRODUCT_LINE foreign key (PRODUCT_LINE_ID) references BIDEMO_PRODUCT_LINE(ID)^
create index IDX_BIDEMO_PRODUCT_PRODUCT_LINE on BIDEMO_PRODUCT (PRODUCT_LINE_ID)^
-- end BIDEMO_PRODUCT
-- begin BIDEMO_ORDER_LINE
alter table BIDEMO_ORDER_LINE add constraint FK_BIDEMO_ORDER_LINE_PRODUCT foreign key (PRODUCT_ID) references BIDEMO_PRODUCT(ID)^
alter table BIDEMO_ORDER_LINE add constraint FK_BIDEMO_ORDER_LINE_ORDER foreign key (ORDER_ID) references BIDEMO_ORDER(ID)^
create index IDX_BIDEMO_ORDER_LINE_PRODUCT on BIDEMO_ORDER_LINE (PRODUCT_ID)^
create index IDX_BIDEMO_ORDER_LINE_ORDER on BIDEMO_ORDER_LINE (ORDER_ID)^
-- end BIDEMO_ORDER_LINE
-- begin BIDEMO_COUNTRY
alter table BIDEMO_COUNTRY add constraint FK_BIDEMO_COUNTRY_TERRITORY foreign key (TERRITORY_ID) references BIDEMO_TERRITORY(ID)^
create index IDX_BIDEMO_COUNTRY_TERRITORY on BIDEMO_COUNTRY (TERRITORY_ID)^
-- end BIDEMO_COUNTRY
-- begin BIDEMO_CITY
alter table BIDEMO_CITY add constraint FK_BIDEMO_CITY_COUNTRY foreign key (COUNTRY_ID) references BIDEMO_COUNTRY(ID)^
create index IDX_BIDEMO_CITY_COUNTRY on BIDEMO_CITY (COUNTRY_ID)^
-- end BIDEMO_CITY
